version: '3.8'

services:
  tasmota-room-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '36884:3600'
    environment:
      - PORT=3600
      - DATABASE_URL=postgresql://user:039153d3-9a68-444b-be96-10c6d1325197@tasmota-db:5432/tasmota?schema=public
      - JWT_SECRET=your_jwt_secret
      - MQTT_BROKER=mqtt://mqtt.laoapps.com
      - MQTT_WS_URL=wss://mqtt.laoapps.com
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=f15c58a3-0d3e-495d-91ca-54b18c13037f
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - BACKEND_KEY=aa65972e-e215-4b12-bd53-aacce0f72050
      - SERVICE_NAME=SMARTCB
      - REDIS_URL=redis://tasmota-redis:6379
      - ADMINGAME_NOCNOC_UUID=3d55d7f0-b611-11ef-8c5b-dfe3a2fc2c00
      - hmVendingUrl=https://vending-service-api5.laoapps.com/zdm8/validateHMVending
      - hmVendingWSUrl=https://vending-service-api5.laoapps.com/zdm8/wsalert
      - NOTILAABX_URL=https://laab-notify.laoapps.com/api/v1/
    networks:
      - tasmota-net
    restart: unless-stopped

networks:
  tasmota-net:
    driver: bridge
    name: tasmota-net        # fixed global name
    external: true           # only on second file? No â€” create it once
    #sudo docker network create tasmota-net