version: "3.7"
services:
  vending-redis-service:
    image: redis
    restart: always
    container_name: vending-redis-service
    #port:
    networks:
      - venderserverservice
  vending-db:
    container_name: vending-db
    image: postgres
    restart: always
    # secrets:
    #   - db-password
    
    volumes:
      - vending-data:/var/lib/postgresql/data
      # - ./initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
      # - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_DB=dbvenderservice
      - POSTGRES_USER=dbvenderserveradmin
      - POSTGRES_PASSWORD=2Grg7Dith14P
    # ports:
    #   -  53432:5432
    networks:
      - venderserverservice
  vender-server-service:
    build: . 
    restart: always
    container_name: vender-server-service
    # image: touyara/orderbillingapi:v1
    # command: npm start
    environment:
      - DATABASE_HOST=vending-db
      - REDIS_HOST=redis://vending-redis-service:6379
      - DATABASE_USER=dbvenderserveradmin
      - DATABASE_DB=dbvenderservice
      - DATABASE_PASSWORD=2Grg7Dith14P
      - VENDING=true
      - PORT=9006
    ports:
      - 51221:31221
      - 51222:31222
      - 51223:31223
      - 51224:31224
      # - 51225:31225
      - 9006:9006
    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - venderserverservice
    depends_on:
      - vending-db
      - vending-redis-service
    links:
      - vending-db
      - vending-redis-service

  
volumes:
  back-notused:
  vending-data:
networks:
  venderserverservice: