version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '31884:3000'
    environment:
      - DATABASE_URL=postgresql://user:039153d3-9a68-444b-be96-10c6d1325197@db:5432/tasmota?schema=public
      - JWT_SECRET=your_jwt_secret
      - MQTT_BROKER=mqtt://mqtt:1883
      - MQTT_WS_URL=wss://mqtt.laoapps.com
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - backendKey=aa65972e-e215-4b12-bd53-aacce0f72050
    depends_on:
      - db
      - mqtt
    volumes:
      - .:/app
    networks:
      - tasmota-net

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=039153d3-9a68-444b-be96-10c6d1325197
      - POSTGRES_DB=tasmota
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasmota-net

  mqtt:
    image: eclipse-mosquitto:2
    ports:
      - '1883:1883'
      - '31883:9001' # WebSocket port
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto.passwd:/mosquitto/config/passwd
    networks:
      - tasmota-net

volumes:
  pgdata:

networks:
  tasmota-net:
    driver: bridge