version: '3.8'
services:
  tasmota-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '31884:3000'
    environment:
      - DATABASE_URL=postgresql://user:039153d3-9a68-444b-be96-10c6d1325197@tasmota-db:5432/tasmota?schema=public
      - JWT_SECRET=your_jwt_secret
      - MQTT_BROKER=mqtt://mqtt:1883
      - MQTT_WS_URL=wss://mqtt.laoapps.com
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=f15c58a3-0d3e-495d-91ca-54b18c13037f
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - BACKEND_KEY=aa65972e-e215-4b12-bd53-aacce0f72050
      - SERVICE_NAME=SMARTCB
      - REDIS_URL=redis://tasmota-redis:6379
    depends_on:
      - tasmota-db
      - tasmota-redis
      - mqtt
    networks:
      - tasmota-net

  tasmota-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=039153d3-9a68-444b-be96-10c6d1325197
      - POSTGRES_DB=tasmota
    ports:
      -  31885:5432  
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tasmota"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - tasmota-net

  mqtt:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    ports:
      - '1883:1883'
      - '31883:9001'
    volumes:
      - mqtt_data:/mosquitto/data
    networks:
      - tasmota-net

  tasmota-redis:
    image: redis:7
    ports:
    - '6379:6379'
    volumes:
    - redis_data:/data
    command: redis-server --save 900 1 --save 300 10 --save 60 10000 --appendonly yes --appendfsync everysec
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - tasmota-net

volumes:
  pgdata:
  mqtt_data:
  redis_data:

networks:
  tasmota-net:
    driver: bridge