version: '3.8'
services:
  tasmota-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '31884:3000'
    environment:
      - DATABASE_URL=postgresql://user:039153d3-9a68-444b-be96-10c6d1325197@tasmota-db:5432/tasmota?schema=public
      - JWT_SECRET=your_jwt_secret
      - MQTT_BROKER=mqtt://mqtt:1883
      - MQTT_WS_URL=wss://mqtt.laoapps.com
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=f15c58a3-0d3e-495d-91ca-54b18c13037f
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - BACKEND_KEY=aa65972e-e215-4b12-bd53-aacce0f72050
      - SERVICE_NAME=SMARTCB
    depends_on:
      - tasmota-db
      - mqtt
    volumes:
      - .:/app
    networks:
      - tasmota-net

  tasmota-db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=039153d3-9a68-444b-be96-10c6d1325197
      - POSTGRES_DB=tasmota
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - tasmota-net

  mqtt:
    build:
      context: ./mqtt
      dockerfile: Dockerfile
    ports:
      - '1883:1883'
      - '31883:9001'
    volumes:
      - mqtt_data:/mosquitto/data
    networks:
      - tasmota-net

volumes:
  pgdata:
  mqtt_data:

networks:
  tasmota-net:
    driver: bridge