version: "3.7"
services:
  vending-redis-service:
    image: redis
    restart: always
    container_name: vending-redis-service
    #port:
    networks:
      - venderserverservice
  vending-db:
    container_name: vending-db
    image: postgres
    restart: always
    # secrets:
    #   - db-password
    
    volumes:
      - vending-data:/var/lib/postgresql/data
      # - ./initdb.sql:/docker-entrypoint-initdb.d/1-initdb.sql
      # - ./initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    environment:
      - POSTGRES_DB=dbvenderservice
      - POSTGRES_USER=dbvenderserveradmin
      - POSTGRES_PASSWORD=2Grg7Dith14P
    ports:
      -  37432:5432
    networks:
      - venderserverservice
  vender-server-service:
    build: . 
    restart: always
    container_name: vender-server-service
    # image: touyara/orderbillingapi:v1
    # command: npm start
    environment:
      
      - DATABASE_HOST=vending-db
      - REDIS_HOST=redis://vending-redis-service:6379
      - REDIS_SERVER_HOST=vending-redis-service
      - REDIS_SERVER_PORT=6379

      - REDIS_HOST=host.docker.internal
      - REDIS_LOCAL_HOST=host.docker.internal
      - REDIS_LOCAL_PORT=6379
      
      # - LAAB_URL=http://host.docker.internal:30000
      # - EPIN_URL=http://host.docker.internal:30001
      # - TEST_CALLBACK:http://host.docker.internal:9006
      # - USERMANAGER_HOST=http://host.docker.internal:4500

      - LAAB_URL=https://laab-api.laoapps.com
      - EPIN_URL=https://epin-api.laoapps.com
      - TEST_CALLBACK=http://laoapps.com:9006
      - USERMANAGER_HOST=https://nocnoc-api.laoapps.com

      - DATABASE_USER=dbvenderserveradmin
      - DATABASE_DB=dbvenderservice
      - DATABASE_PASSWORD=2Grg7Dith14P
      - VENDING=true
      - PORT=9006
      - KIOSKLAABPORT=31224


      - SERVICE_NAME=ADMINVENDINGSERVICE
      - SERVICE_BACKEND_KEY=cf4f51eb-c999-4077-b7ca-110a66d563e5
    ports:
      - 51221:31221
      - 51222:31222
      - 51223:31223
      - 51224:31224
      # - 51225:31225
      - 51226:31226
      - 9006:9006
    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - venderserverservice
    depends_on:
      - vending-db
      - vending-redis-service
    links:
      - vending-db
      - vending-redis-service

  
volumes:
  back-notused:
  vending-data:
networks:
  venderserverservice: