version: "3.7"
services:
vender-service:
    build: . 
    restart: always
    container_name: vender-service
    # image: touyara/orderbillingapi:v1
    # command: npm start
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_USER=dbvenderadminservice
      - DATABASE_DB=dbvenderservice
      - DATABASE_PASSWORD=1MqMI8eT32Jj
      - PORT=34214
    ports:
      - 34214:34214
    secrets:
      - db-password
    volumes:
      - .:/app
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - back-notused:/opt/app/node_modules
    networks:
      - venderservice
    depends_on:
      - vender-service-service
      #- postgresql
      #- redis

  
volumes:
  back-notused:
networks:
  venderservice: