version: '3.8'

services:
  tasmota-room-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '36884:3000'
    environment:
      - DATABASE_URL=postgresql://user:${POSTGRES_PASSWORD}@tasmota-room-db:15432/tasmota-room?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - MQTT_BROKER=mqtt://mqtt:1883
      - MQTT_WS_URL=wss://mqtt.laoapps.com
      - MQTT_USERNAME=admin
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - USERMANAGER_URL=https://nocnoc-api.laoapps.com
      - BACKEND_KEY=${BACKEND_KEY}
      - SERVICE_NAME=SMARTCB
      - REDIS_URL=redis://tasmota-room-redis:16379
      - ADMINGAME_NOCNOC_UUID=${ADMINGAME_NOCNOC_UUID}
      - hmVendingUrl=https://vending-service-api5.laoapps.com/zdm8/validateHMVending
      - hmVendingWSUrl=https://vending-service-api5.laoapps.com/zdm8/wsalert
      - NOTILAABX_URL=https://laab-notify.laoapps.com/api/v1/
    depends_on:
      tasmota-room-db:
        condition: service_healthy
      tasmota-room-redis:
        condition: service_healthy
    networks:
      - tasmota-net
    restart: unless-stopped

  tasmota-room-db:
    image: postgres:15
    command: -p 15432                                   # This forces Postgres to listen on 15432 inside the container
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=tasmota-room
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d tasmota-room -p 15432"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - tasmota-net
    restart: unless-stopped

  tasmota-room-redis:
    image: redis:7
    command: redis-server --port 16379 --save 900 1 --save 300 10 --save 60 10000 --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "16379", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - tasmota-net
    restart: unless-stopped

volumes:
  pgdata:
  redis_data:

networks:
  tasmota-net:
    driver: bridge